// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/llmons/Lmusic/internal/base/conf"
	"github.com/llmons/Lmusic/internal/base/server"
	"github.com/llmons/Lmusic/internal/controller"
	"github.com/llmons/Lmusic/internal/router"
	"github.com/llmons/Lmusic/internal/service"
)

// Injectors from wire.go:

func initApplication(debug bool, serverConf *conf.Server) (*gin.Engine, error) {
	neteaseService := service.NewNeteaseService()
	neteaseController := controller.NewNeteaseController(neteaseService)
	tencentService := service.NewTencentService()
	tencentController := controller.NewTencentController(tencentService)
	apiRouter := router.NewAPIRouter(neteaseController, tencentController)
	engine := server.NewHTTPServer(debug, apiRouter)
	return engine, nil
}
