// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package main

import (
	"github.com/gin-gonic/gin"
	"github.com/llmons/Lmusic/internal/base/conf"
	"github.com/llmons/Lmusic/internal/base/server"
)

// Injectors from wire.go:

func initApplication(debug bool, serverConf *conf.Server) (*gin.Engine, error) {
	engine := server.NewHTTPServer(debug)
	return engine, nil
}
